project:
  type: website
  output-dir: _site
  resources:
    - files/**
  pre-render:
    - _scripts/pre_render_cv.sh
    - _scripts/pre_render_research.sh

execute:
  freeze: auto

website:
  title: "Ryan C. Briggs"
  navbar:
    left:
      - text: "CV"
        href: files/cv.pdf
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Students"
        href: students.qmd
      - text: "Blog"
        href: blog/index.qmd

format:
  html:
    theme:
      - default
      - custom.scss
    css: styles.css
    toc: false
